# Generated by Django 5.2.4 on 2025-07-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("author", models.CharField()),
                ("content", models.TextField()),
                ("ingredient", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
